language: go
go:
- 1.12.x
sudo: required
services:
- docker
script:
- sudo apt update && sudo apt install libzmq3-dev libsodium-dev
- export GO111MODULE=on
- make setup
- make linter-install
- make ci
- make
- ./build_static.sh
deploy:
  provider: releases
  api_key:
    secure: ZAMSIFD7qkZvXwT9/6M4ph1i2OEeEc4KsZ1PfovxLcPuQ4+vKtGjS2/E7WVfqAVrUs6iF/AEENtJJliq4ahgVRQb/Y0bWIIcByIfJSky/czJIXlv0Zc6JC6uiJzgNu3zVAlOUHkABGkWXE/vBD/N4v38oyOst2HSc+iHnuvJqt1Efi8gxnx8Map5yvGY+FJYkqe29zSNMYzZo4ezapgxGe5dDbb3aB5GI0Fam/BD6hKDn6efuBj6vx7YfE7aZMcKv7gy/pBzxA8hvIDqgkV4sQWuJ7ZGziqoR1jsPXg4CohQTFUNxbjUJe7EBFVflt8ONca22zwiJbNSgxYLx/BJLzExATLawa86Bjd+GNoZUS7MVdmz1GUcWYm4pMKKXG+urrefbbInv+AvVt5rn/XPGKOnX7afRIaigchW3sQlM5izlf6y3VoAwcJ93uR3W/TvEQAKX1B4813h5RzIkbutQj1YU0D1nUkaO1hS2p98UVPpCR7igzSKyyoslDfvnJBcGy1251Rc9Qm8LJleGIgRqHJXlcejDq1MzyFDf9L2Q/RW5FfStNKKRauWScolY2vbyMPLaRlOljRCXsOlufTeXPuREMYQznXsek8bHsJY1/HW6UU94mInQj2biWzbY/gkFM2suusmwbS4dnpvuV30MmOTy8vz9nVkI5xjQs+4PRk=
  file: asgard-query
  skip_cleanup: true
  on:
    tags: true
