language: go
go:
- 1.12.x
sudo: required
services:
- docker
script:
- sudo apt update && sudo apt install libzmq3-dev libsodium-dev
- export GO111MODULE=on
- make setup
- make linter-install
- make ci
- make
- ./build_static.sh
